### ISSUE TITLE
Documentation link should point to interactive documentation

### ISSUE THREAD

**Issue by brylie** [maasglobal/maas-api.org#1]
#Context
The 'API Documentation' link currently points to the TSP reference implementation repository. This was done because the TSP Reference repo is more 'up to date' than the previous Swagger documentation.

While accuracy is important, it still leaves a lot to the developer to figure out a series of JSON schema files.

# Goal
Improve developer experience by linking to interactive documentation (i.e. docs in Swagger UI).

# Task
- [ ] Update Open API spec files in [MaaS TSP API](https://github.com/maasglobal/maas-tsp-api/) repo
- [x] Host MaaS TSP API repo Swagger UI on GH Pages
- [x] Update 'API Documentation' link (this repo) to point to Swagger UI
